### ISSUE TITLE
explore the dataset

### ISSUE THREAD

**Issue by zhaoyanpeng** [McGill-NLP/imagecode#2]
Hey thank you for sharing the code and dataset! I am wondering if there is a plan to build an online demo for the dataset (e.g., [COCO Explorer](https://cocodataset.org/#explore)), so we can explore image sets easily.

**Comment by sivareddyg** [comment]
hi @zhaoyanpeng, thanks for your interest! We are in the process of creating an explorer, but that may not happen in April likely due to the semester's busyness.

**Comment by BennoKrojer** [comment]
Hi, I am sorry I haven't posted an update since Siva responded. There has been a demo since May!
https://huggingface.co/spaces/BennoKrojer/imagecode-demo
