### ISSUE TITLE
Could you provide checkpoint for the best performing model

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [McGill-NLP/imagecode#3]
Thank you for the great dataset first,
but checkpoints/CONTRA_clip_best__36_4e-06_30_1395526.pt is missing in README.md
```
python3 contextual.py --lr 2e-6 --lr_head 1e-4 -b 36 -m ViT-B/16 --fusion mult -a gelu --logit_scale 1000 --finetuned_checkpoint_path checkpoints/CONTRA_clip_best__36_4e-06_30_1395526.pt --add_input --frozen_clip --positional
```
Could you provide this checkpoint?
Thank you in advance.

**Comment by BennoKrojer** [comment]
Hi,
Thanks for pointing out that this is still missing. I uploaded it and it is in the README at the end of the Data section.
Let me know if it works or if there are more questions!
