### ISSUE TITLE
Can not run the code

### ISSUE THREAD

**Issue by LisaS12345** [McGill-NLP/imagecode#4]
Dear, For my research at the university, I am researching the paper Image Retrieval from Contextual Descriptions. For this I need to research the reproducibility and had downloaded the code and followed the instructions. However, I currently get the error that it does not know various packages, but when I ask my terminal, it does recognize them. packages that it has a problem with is for example yaml. Does anyone have the same problem and a way to solve it. Sincerely, Lisa

**Comment by BennoKrojer** [comment]
See my email!
Will close this once it is resolved hopefully.
